### ISSUE TITLE
Flag for plot.py to do dynamic axis scaling (accigue)

### ISSUE THREAD

**Issue by accigue** [dirkbeer/adsb-analysis#5]
Perhaps a command line flag for choosing dynamic axis scaling vs the static 300 miles and .7 probability. That would still allow easy comparisons for overlays but also let the chart naturally flow for those that want to see all the data, who use the flag.

**Comment by dirkbeer** [comment]
Added a command line flag --dynamic-limits or -dl for short. Let me know if it works for you.

**Comment by accigue** [comment]
Works with a simple pass of -dl as arg.  Chart scale updated properly.  Thanks.
